/**
 * Atlas destinations and modal content by locale (ES/EN).
 * Used by DestinationsFlagship to render the Atlas of Exploration.
 */

export type AtlasDestination = {
  id: string
  name: string
  slug: string
  region: string
  coordinates: string
  altitude: string
  season: string
  desc: string
  highlight: string
  image: string
  tags: string[]
}

export type AtlasModalData = {
  subtitle: string
  intro: string
  whyGo: string[]
  highlights: string[]
  keyPlaces: string[]
  bestSeason: { when: string; climate: string; expect: string }
  travelerProfile: {
    experienceType: string
    travelerProfile: string
    suggestedStay: string
    culturalLevel: string
    landscapeType: string
    role: string
  }
  cta: { primary: string; secondary: string }
}

const destinationsEs: AtlasDestination[] = [
  { id: '01', name: 'Creel', slug: 'creel', region: 'Sierra Tarahumara (Central)', coordinates: '27.7523° N, 107.6358° W', altitude: '2,350 msnm', season: 'Todo el año', desc: 'El corazón latente de la Sierra. Campamento base para adentrarse en bosques antiguos, valles de formaciones milenarias y la herencia viva de la cultura Rarámuri.', highlight: 'Base de Expedición', image: '/images/destinations/creel.jpg', tags: ['Pueblo Mágico', 'Misticismo'] },
  { id: '02', name: 'Barrancas del Cobre', slug: 'barrancas-del-cobre', region: 'Sistema de Cañones', coordinates: '27.5333° N, 107.7667° W', altitude: 'Variable - Abismo Profundo', season: 'Recomendado Otoño-Primavera', desc: 'Un laberinto de cañones que desafía toda escala humana. Es un reino salvaje, inmenso, el epicentro indiscutible de la aventura en México.', highlight: 'Cañones Monstruosos', image: '/images/destinations/barrancas-del-cobre.jpg', tags: ['Aventura Extrema', 'Monumental'] },
  { id: '03', name: 'Divisadero', slug: 'divisadero', region: 'Circuito Barrancas', coordinates: '27.5338° N, 107.8252° W', altitude: '2,400 msnm', season: 'Todo el año', desc: 'Donde la tierra se desgarra majestuosa. El mirador icónico del Tren CHEPE y el cruce audaz del teleférico inmerso en la niebla y el vacío.', highlight: 'Punto Panorámico', image: '/images/destinations/divisadero.jpg', tags: ['Teleférico', 'Fotografía'] },
  { id: '04', name: 'El Fuerte', slug: 'el-fuerte', region: 'Sinaloa Norte', coordinates: '26.4172° N, 108.6219° W', altitude: '90 msnm', season: 'Invierno y Primavera', desc: 'Elegancia colonial vibrante a las orillas de un río histórico. Es el umbral perfecto, un prólogo cálido antes del ascenso épico a la alta montaña.', highlight: 'Magia Colonial', image: 'https://drive.google.com/uc?export=view&id=1QBGJrkjDhMGm6IntVPA9QvnAsa9FZer3', tags: ['Historia', 'Pueblo Mágico'] },
  { id: '05', name: 'Los Mochis', slug: 'los-mochis', region: 'Costa Pacífico N.O.', coordinates: '25.7928° N, 108.9895° W', altitude: '10 msnm', season: 'Otoño a Primavera', desc: 'Donde el Mar de Cortés besa la tierra, dando inicio (o fin) a la vía férrea más asombrosa de Latinoamérica. Un polo de riqueza gastronómica y portuaria.', highlight: 'Puerto y Tren', image: 'https://drive.google.com/uc?export=view&id=1EInQ_98ctAvzH6r9A2ZOrIvbKu1rWlnR', tags: ['Mariscos', 'Punto Cero'] },
  { id: '06', name: 'Cerocahui', slug: 'cerocahui', region: 'Valle Escóndido (Urique)', coordinates: '27.3197° N, 108.0264° W', altitude: '1,600 msnm', season: 'Otoño - Primavera', desc: 'Un remoto valle abrazado por montañas, resguardando una antigua misión jesuita y viñedos centenarios de altura. Un refugio de introspección absoluta.', highlight: 'Retiro Jesuita', image: '/images/destinations/cerocahui-iglesia.jpg', tags: ['Vino', 'Mirador del Gallego'] },
  { id: '07', name: 'Basaseachi', slug: 'basaseachi', region: 'Altos de Candameña', coordinates: '28.1878° N, 108.2148° W', altitude: '2,100 msnm', season: 'Verano y Otoño (Lluvias)', desc: 'Hogar de la cascada permanente más alta de México. Una grieta monumental en la Sierra donde el agua, la piedra y el bosque crean una de las escenas más imponentes del norte del país.', highlight: 'Naturaleza Colosal', image: 'https://drive.google.com/uc?export=view&id=1-yd2RnTEhrhOgzmHUWPhBQdEbGoGirUw', tags: ['Senderismo', 'Cascada'] },
  { id: '08', name: 'Guachochi', slug: 'guachochi', region: 'Alta Sierra Tarahumara', coordinates: '26.8197° N, 107.0675° W', altitude: '2,280 msnm', season: 'Ideal Marzo-Noviembre', desc: 'La verdadera metrópoli Rarámuri. Entre sus cumbres y barrancas se esconde Sinforosa y la mística de Kokoyome, una tierra puramente originaria.', highlight: 'Cultura Originaria', image: 'https://drive.google.com/uc?export=view&id=13v4cPXbF_m0g7Xw9l99k0CIjxyQaUBPE', tags: ['Rutas Indígenas', 'Aislamiento'] },
  { id: '09', name: 'Cuauhtémoc', slug: 'cuauhtemoc', region: 'Llanos Menonitas', coordinates: '28.4069° N, 106.8653° W', altitude: '2,040 msnm', season: 'Todo el año', desc: 'El encuentro surrealista de las praderas. Aquí, la asombrosa paz de las colonias Menonitas convive con la vasta región manzanera más grande del país.', highlight: 'Corredor Cultural', image: 'https://drive.google.com/uc?export=view&id=1SvD1FAN2zEL7BOdD3enpED0ZFEEbBfqo', tags: ['Gastronomía Menonita', 'Mestizaje'] },
  { id: '10', name: 'Chihuahua', slug: 'chihuahua', region: 'Desierto y Llanura', coordinates: '28.6320° N, 106.0691° W', altitude: '1,420 msnm', season: 'Otoño y Primavera', desc: 'El corazón señorial del norte. Ciudad de cantera, ecos de la Revolución y haciendas inmensas. El arranque clásico para cruzar la gran Sierra.', highlight: 'Capital Histórica', image: 'https://drive.google.com/uc?export=view&id=1kV_Aolq398pBAjpdOOhHAA6cQGfKtzkD', tags: ['Orígenes', 'Arquitectura'] },
]

const destinationsEn: AtlasDestination[] = [
  { id: '01', name: 'Creel', slug: 'creel', region: 'Sierra Tarahumara (Central)', coordinates: '27.7523° N, 107.6358° W', altitude: '2,350 masl', season: 'All year', desc: 'The beating heart of the Sierra. Base camp to explore ancient forests, valleys of millennial formations, and the living heritage of Rarámuri culture.', highlight: 'Expedition Base', image: '/images/destinations/creel.jpg', tags: ['Magic Town', 'Mysticism'] },
  { id: '02', name: 'Copper Canyon', slug: 'barrancas-del-cobre', region: 'Canyon System', coordinates: '27.5333° N, 107.7667° W', altitude: 'Variable – Deep Abyss', season: 'Fall–Spring recommended', desc: 'A maze of canyons that defies human scale. A wild, immense realm and the undisputed epicenter of adventure in Mexico.', highlight: 'Monumental Canyons', image: '/images/destinations/barrancas-del-cobre.jpg', tags: ['Extreme Adventure', 'Monumental'] },
  { id: '03', name: 'Divisadero', slug: 'divisadero', region: 'Canyon Circuit', coordinates: '27.5338° N, 107.8252° W', altitude: '2,400 masl', season: 'All year', desc: 'Where the earth tears open in majesty. The iconic viewpoint of the CHEPE Train and the bold cable car crossing through mist and void.', highlight: 'Panoramic Point', image: '/images/destinations/divisadero.jpg', tags: ['Cable car', 'Photography'] },
  { id: '04', name: 'El Fuerte', slug: 'el-fuerte', region: 'Northern Sinaloa', coordinates: '26.4172° N, 108.6219° W', altitude: '90 masl', season: 'Winter and Spring', desc: 'Vibrant colonial elegance on the banks of a historic river. The perfect threshold, a warm prologue before the epic ascent into the high mountains.', highlight: 'Colonial Magic', image: 'https://drive.google.com/uc?export=view&id=1QBGJrkjDhMGm6IntVPA9QvnAsa9FZer3', tags: ['History', 'Magic Town'] },
  { id: '05', name: 'Los Mochis', slug: 'los-mochis', region: 'N.W. Pacific Coast', coordinates: '25.7928° N, 108.9895° W', altitude: '10 masl', season: 'Fall to Spring', desc: 'Where the Sea of Cortez meets the land, where the most astonishing railway in Latin America begins (or ends). A hub of gastronomic and port wealth.', highlight: 'Port & Train', image: 'https://drive.google.com/uc?export=view&id=1EInQ_98ctAvzH6r9A2ZOrIvbKu1rWlnR', tags: ['Seafood', 'Ground Zero'] },
  { id: '06', name: 'Cerocahui', slug: 'cerocahui', region: 'Hidden Valley (Urique)', coordinates: '27.3197° N, 108.0264° W', altitude: '1,600 masl', season: 'Fall – Spring', desc: 'A remote valley embraced by mountains, sheltering an ancient Jesuit mission and century-old high-altitude vineyards. A refuge of absolute introspection.', highlight: 'Jesuit Retreat', image: '/images/destinations/cerocahui-iglesia.jpg', tags: ['Wine', 'Gallego Overlook'] },
  { id: '07', name: 'Basaseachi', slug: 'basaseachi', region: 'Candameña Highlands', coordinates: '28.1878° N, 108.2148° W', altitude: '2,100 masl', season: 'Summer and Fall (Rain)', desc: 'Home to Mexico’s tallest permanent waterfall. A monumental cleft in the Sierra where water, rock, and forest create one of the most imposing scenes in the north.', highlight: 'Colossal Nature', image: 'https://drive.google.com/uc?export=view&id=1-yd2RnTEhrhOgzmHUWPhBQdEbGoGirUw', tags: ['Hiking', 'Waterfall'] },
  { id: '08', name: 'Guachochi', slug: 'guachochi', region: 'High Sierra Tarahumara', coordinates: '26.8197° N, 107.0675° W', altitude: '2,280 masl', season: 'Ideal March–November', desc: 'The true Rarámuri heartland. Among its peaks and canyons lie Sinforosa and the mystique of Kokoyome—a land that is purely indigenous.', highlight: 'Indigenous Culture', image: 'https://drive.google.com/uc?export=view&id=13v4cPXbF_m0g7Xw9l99k0CIjxyQaUBPE', tags: ['Indigenous Routes', 'Remoteness'] },
  { id: '09', name: 'Cuauhtémoc', slug: 'cuauhtemoc', region: 'Mennonite Plains', coordinates: '28.4069° N, 106.8653° W', altitude: '2,040 masl', season: 'All year', desc: 'The surreal encounter of the prairies. Here, the striking peace of Mennonite colonies meets the country’s largest apple-growing region.', highlight: 'Cultural Corridor', image: 'https://drive.google.com/uc?export=view&id=1SvD1FAN2zEL7BOdD3enpED0ZFEEbBfqo', tags: ['Mennonite Cuisine', 'Cultural Mix'] },
  { id: '10', name: 'Chihuahua', slug: 'chihuahua', region: 'Desert and Plains', coordinates: '28.6320° N, 106.0691° W', altitude: '1,420 masl', season: 'Fall and Spring', desc: 'The stately heart of the north. A city of stone, echoes of the Revolution, and vast haciendas. The classic starting point to cross the great Sierra.', highlight: 'Historic Capital', image: 'https://drive.google.com/uc?export=view&id=1kV_Aolq398pBAjpdOOhHAA6cQGfKtzkD', tags: ['Origins', 'Architecture'] },
]

const modalDataEs: Record<string, AtlasModalData> = {
  'creel': { subtitle: 'Campamento base del corazón de la Sierra', intro: 'Creel late en el centro mismo de la Sierra Tarahumara: un pueblo de madera y piedra donde el tiempo se mide en rutas y en historias Rarámuri. Aquí no se pasa de largo; aquí se establece base para adentrarse en bosques de pinos infinitos, valles de hongos y ranas petrificadas, y en la presencia viva de una cultura que ha resistido siglos. Es el punto de partida perfecto para quien busca profundidad, no solo postales.', whyGo: ['Puerta de entrada natural a la Sierra Tarahumara', 'Conexión auténtica con comunidades Rarámuri', 'Naturaleza monumental a minutos del pueblo', 'Logística estratégica para rutas hacia Divisadero y Barrancas', 'Experiencias icónicas: Valle de los Hongos, Arareco, misiones'], highlights: ['Paisajes de bosque y valles rocosos', 'Cultura Rarámuri viva', 'Gastronomía local y artesanías', 'Aventura suave a intensa', 'Miradores y lagos', 'Base para tours al CHEPE y Barrancas'], keyPlaces: ['Lago de Arareco', 'Valle de los Hongos', 'Valle de las Ranas', 'Cueva Tarahumara', 'Misión de San Ignacio', 'Conexión hacia Divisadero y Barrancas del Cobre'], bestSeason: { when: 'Todo el año; otoño y primavera óptimos.', climate: 'Templado de montaña; noches frías en invierno.', expect: 'Verano lluvioso y verde; invierno seco y cielos claros.' }, travelerProfile: { experienceType: 'Naturaleza y cultura', travelerProfile: 'Viajero curioso, familias, parejas, aventureros moderados', suggestedStay: '2–4 noches como base', culturalLevel: 'Alta — encuentro directo con comunidades', landscapeType: 'Bosque de pino, valles rocosos, lagos', role: 'Base operativa principal' }, cta: { primary: 'Ver paquetes relacionados', secondary: 'Hablar con un asesor' } },
  'barrancas-del-cobre': { subtitle: 'El epicentro indiscutible de la aventura en México', intro: 'Las Barrancas del Cobre no son un solo lugar: son un sistema de cañones que multiplica la escala humana hasta volverla insignificante. Aquí la tierra se abre en abismos de más de mil metros, el tren serpentea por las laderas y la aventura — tirolesas, trekking, miradores — se vive con una intensidad que pocos destinos en el mundo pueden igualar. Es naturaleza pura, salvaje y monumental.', whyGo: ['Uno de los sistemas de cañones más grandes del mundo', 'Experiencias de aventura de nivel internacional', 'Vistas que redefinen la idea de paisaje', 'Cruce del CHEPE y teleférico como experiencias únicas', 'Conexión con Divisadero, Creel y la Sierra'], highlights: ['Cañones y abismos', 'Teleférico y tren', 'Aventura extrema y moderada', 'Fotografía y miradores', 'Naturaleza virgen', 'Tours organizados desde Creel y Divisadero'], keyPlaces: ['Mirador del Parque de Aventura', 'Teleférico Barrancas', 'Trazado del Tren CHEPE', 'Sistema de cañones Urique–Tararecua', 'Puntos de tirolesa y rappel', 'Vistas hacia la Barranca del Cobre'], bestSeason: { when: 'Otoño a primavera; evitar lluvias intensas de verano.', climate: 'Variable según altura; fresco en altos, cálido en fondo de barranca.', expect: 'Cielos despejados en temporada seca; verde intenso tras lluvias.' }, travelerProfile: { experienceType: 'Aventura y naturaleza extrema', travelerProfile: 'Aventureros, fotógrafos, parejas activas', suggestedStay: '1–3 noches según circuito', culturalLevel: 'Media — paisaje y experiencia física primero', landscapeType: 'Cañones, abismos, bosque', role: 'Destino estrella del circuito' }, cta: { primary: 'Ver paquetes relacionados', secondary: 'Explorar experiencias desde aquí' } },
  'divisadero': { subtitle: 'El mirador icónico del Tren CHEPE y el vacío del teleférico', intro: 'Divisadero es el instante en que el viaje se detiene ante el abismo: tres barrancas convergen a tus pies y el silencio solo lo rompe el viento. El teleférico cruza el vacío entre riscos; el tren hace su parada obligada. Aquí la experiencia es puramente visual y sensorial — una inmersión en la escala brutal de la Sierra, con infraestructura premium que no le resta autenticidad al lugar.', whyGo: ['Vista de las Tres Barrancas en un solo punto', 'Teleférico más largo de Latinoamérica', 'Parada emblemática del Tren CHEPE', 'Fotografía y atardeceres inolvidables', 'Acceso directo a aventura y tranquilidad'], highlights: ['Miradores panorámicos', 'Teleférico', 'Fotografía y paisaje', 'Cultura y artesanía local', 'Atardeceres', 'Conectividad con Creel y Barrancas'], keyPlaces: ['Mirador de las Tres Barrancas', 'Estación del Tren CHEPE', 'Teleférico Barrancas', 'Pueblo de Divisadero', 'Vista a Urique y Tararecua', 'Senderos y puntos fotográficos'], bestSeason: { when: 'Todo el año; otoño y primavera con mejor luz.', climate: 'Fresco en la altura; soleado la mayor parte del año.', expect: 'Niebla matutina posible; tardes despejadas ideales para fotografía.' }, travelerProfile: { experienceType: 'Panorámico y aventura suave', travelerProfile: 'Todos los perfiles; imprescindible para quien hace el CHEPE', suggestedStay: '1–2 noches', culturalLevel: 'Media — impacto visual y experiencia del tren', landscapeType: 'Cañones, miradores, vacío', role: 'Punto panorámico y conexión' }, cta: { primary: 'Ver paquetes relacionados', secondary: 'Cotizar viaje' } },
  'el-fuerte': { subtitle: 'Umbral colonial antes del ascenso épico a la Sierra', intro: 'El Fuerte es el prólogo perfecto al viaje: un Pueblo Mágico donde la arquitectura colonial y el rumor del Río Fuerte cuentan siglos de historia. Aquí se siente aún el paso de los conquistadores y el legado de las culturas originarias. Es el punto de partida occidental del Tren CHEPE para quien viene del mar; un lugar para respirar, caminar y preparar el espíritu antes de subir a la montaña.', whyGo: ['Pueblo Mágico con arquitectura colonial intacta', 'Punto de partida del CHEPE desde la costa', 'Río Fuerte y naturaleza ribereña', 'Historia y leyendas (El Zorro)', 'Gastronomía y tranquilidad'], highlights: ['Historia y arquitectura', 'Río y naturaleza', 'Gastronomía local', 'Danzas y tradiciones', 'Base para el CHEPE', 'Identidad colonial'], keyPlaces: ['Centro histórico y Plaza de Armas', 'Río Fuerte y malecón', 'Museo y edificios coloniales', 'Comunidades cercanas', 'Estación del Tren CHEPE', 'Miradores y alrededores'], bestSeason: { when: 'Invierno y primavera; evitar calor extremo de verano.', climate: 'Cálido; templado en invierno.', expect: 'Días soleados; noches agradables; ideal para caminata y fotografía.' }, travelerProfile: { experienceType: 'Historia y naturaleza suave', travelerProfile: 'Culturales, familias, quienes inician ruta CHEPE', suggestedStay: '1–2 noches', culturalLevel: 'Alta — historia y patrimonio', landscapeType: 'Colonial, río, vegetación', role: 'Base de inicio de ruta' }, cta: { primary: 'Ver paquetes relacionados', secondary: 'Hablar con un asesor' } },
  'los-mochis': { subtitle: 'Donde el Mar de Cortés encuentra el inicio del tren más asombroso', intro: 'Los Mochis es la puerta del Pacífico a la Sierra Tarahumara: una ciudad que vive del mar y del campo, con una gastronomía que atrae a viajeros de todo el país. Aquí empieza — o termina — el recorrido del CHEPE para quienes vienen de la costa. No es solo un punto logístico: es una oportunidad de mariscos frescos, ambiente portuario y la emoción de subir al tren rumbo a la montaña.', whyGo: ['Inicio o fin del Tren CHEPE desde la costa', 'Gastronomía de mar y tierra de primer nivel', 'Conectividad aérea y terrestre', 'Puerto Topolobampo y Mar de Cortés', 'Logística ideal para rutas Creel–Divisadero'], highlights: ['Mariscos y gastronomía', 'Puerto y playa', 'Tren CHEPE', 'Servicios y conectividad', 'Naturaleza costera', 'Base de operaciones'], keyPlaces: ['Centro y zona gastronómica', 'Puerto Topolobampo', 'Estación del CHEPE', 'Parques y malecón', 'Mercados locales', 'Conexión a El Fuerte y Sinaloa'], bestSeason: { when: 'Otoño a primavera; verano muy cálido.', climate: 'Cálido costero; humedad en temporada de lluvias.', expect: 'Sol y brisa la mayor parte del año; ideal para mariscos y salidas.' }, travelerProfile: { experienceType: 'Gastronomía y logística', travelerProfile: 'Viajeros que inician/terminan ruta, amantes del mar', suggestedStay: '1 noche típica', culturalLevel: 'Media — ciudad y puerto', landscapeType: 'Costa, puerto, ciudad', role: 'Punto cero de ruta costera' }, cta: { primary: 'Ver paquetes relacionados', secondary: 'Explorar experiencias desde aquí' } },
  'cerocahui': { subtitle: 'Refugio jesuita y viñedos en un valle escondido', intro: 'Cerocahui aparece como un secreto bien guardado: un valle rodeado de montañas donde una misión jesuita y viñedos de altura conviven con el silencio. Aquí la experiencia es de retiro e introspección — caminatas suaves, vistas al Cañón de Urique, vino local y la sensación de estar muy lejos del ruido del mundo. Es el destino para quien busca profundidad y calma.', whyGo: ['Misión jesuita y patrimonio histórico', 'Viñedos de altura y vino local', 'Vistas al Cañón de Urique desde el Mirador del Gallego', 'Tranquilidad y retiro', 'Acceso a Barrancas con menor flujo turístico'], highlights: ['Historia y misión', 'Vino y viñedos', 'Miradores al cañón', 'Senderismo suave', 'Cultura local', 'Estancia de retiro'], keyPlaces: ['Misión de Cerocahui', 'Mirador del Gallego', 'Viñedos locales', 'Valle de Cerocahui', 'Conexión a Urique', 'Senderos y miradores'], bestSeason: { when: 'Otoño a primavera; verano con lluvias.', climate: 'Templado de valle; noches frescas.', expect: 'Otoño ideal para viñedos; primavera verde y florida.' }, travelerProfile: { experienceType: 'Cultura y naturaleza serena', travelerProfile: 'Viajeros en busca de calma, parejas, retiros', suggestedStay: '1 noche', culturalLevel: 'Alta — misión y vino', landscapeType: 'Valle, viñedos, cañón', role: 'Destino de estancia' }, cta: { primary: 'Ver paquetes relacionados', secondary: 'Cotizar viaje' } },
  'basaseachi': { subtitle: 'La cascada permanente más alta de México', intro: 'Basaseachi alberga la cascada permanente más alta de México: más de 240 metros de caída libre en un cañón de roca y bosque de pinos. Agua, piedra y naturaleza se unen en una de las escenas más imponentes del norte del país. Senderos, miradores y el rumor constante del agua convierten la visita en una experiencia que exige tiempo y respeto.', whyGo: ['Cascada de Basaseachi: la cascada permanente más alta de México', 'Bosque de pino y paisaje de barranca', 'Senderismo y miradores espectaculares', 'Naturaleza virgen y bien conservada', 'Experiencia de un día o pernocte'], highlights: ['Cascada', 'Senderismo', 'Bosque y naturaleza', 'Fotografía', 'Aventura moderada', 'Paisaje monumental'], keyPlaces: ['Cascada de Basaseachi', 'Mirador superior e inferior', 'Senderos del parque', 'Bosque de Candameña', 'Conexión desde Creel o Chihuahua'], bestSeason: { when: 'Verano y otoño — mayor caudal; primavera también viable.', climate: 'Templado a fresco; lluvias en temporada.', expect: 'Cascada más impresionante con lluvias recientes; verano verde y húmedo.' }, travelerProfile: { experienceType: 'Naturaleza y senderismo', travelerProfile: 'Aventureros moderados, familias activas, fotógrafos', suggestedStay: '1–2 noches', culturalLevel: 'Baja — protagonista es la naturaleza', landscapeType: 'Cascada, bosque, cañón', role: 'Destino de naturaleza' }, cta: { primary: 'Ver paquetes relacionados', secondary: 'Hablar con un asesor' } },
  'guachochi': { subtitle: 'La metrópoli Rarámuri y la puerta a la Barranca de Sinforosa', intro: 'Guachochi es el corazón más auténtico de la Sierra Tarahumara: un lugar donde la cultura Rarámuri no es folclor, sino vida cotidiana. Desde aquí se accede a la imponente Barranca de Sinforosa y a comunidades que mantienen lengua, tradiciones y resistencia. Es un destino para viajeros que buscan verdadera profundidad cultural y paisajes que pocos llegan a conocer.', whyGo: ['Mayor concentración de población Rarámuri', 'Acceso a la Barranca de Sinforosa', 'Cultura viva y auténtica', 'Paisajes poco masificados', 'Experiencias de turismo comunitario'], highlights: ['Cultura Rarámuri', 'Barranca de Sinforosa', 'Turismo comunitario', 'Senderismo y aventura', 'Identidad originaria', 'Miradores remotos'], keyPlaces: ['Guachochi cabecera', 'Barranca de Sinforosa', 'Comunidades Rarámuri', 'Kokoyome y alrededores', 'Miradores y rutas', 'Misión y centros culturales'], bestSeason: { when: 'Marzo a noviembre; evitar frío extremo en invierno.', climate: 'Templado de altura; noches frías.', expect: 'Temporada seca ideal para caminatas; lluvias verano limitan algunas rutas.' }, travelerProfile: { experienceType: 'Cultura originaria y aventura', travelerProfile: 'Viajeros conscientes, culturales, aventureros', suggestedStay: '2–4 noches', culturalLevel: 'Muy alta — inmersión Rarámuri', landscapeType: 'Sierra, barranca, comunidades', role: 'Destino de profundidad' }, cta: { primary: 'Ver paquetes relacionados', secondary: 'Explorar experiencias desde aquí' } },
  'cuauhtemoc': { subtitle: 'Praderas Menonitas y la manzana del norte de México', intro: 'Cuauhtémoc sorprende: en medio del norte árido, colonias Menonitas mantienen un modo de vida que parece detenido en el tiempo. Quesos, manzanas, carretas y silencio. La región es además el gran productor de manzana del país. Aquí la experiencia es cultural y gastronómica — un contraste único con la Sierra y el desierto que lo rodean.', whyGo: ['Colonias Menonitas y cultura única', 'Gastronomía menonita (queso, embutidos)', 'Región manzanera más importante de México', 'Contraste con la Sierra y el desierto', 'Tranquilidad y seguridad'], highlights: ['Cultura Menonita', 'Gastronomía y mercados', 'Campos y praderas', 'Artesanía y productos locales', 'Fotografía y paisaje', 'Experiencia de contraste'], keyPlaces: ['Colonias Menonitas', 'Mercados y queserías', 'Campos manzaneros', 'Cuauhtémoc ciudad', 'Rutas de día', 'Conexión a Creel y Chihuahua'], bestSeason: { when: 'Todo el año; cosecha manzana en otoño.', climate: 'Seco y templado; inviernos fríos.', expect: 'Otoño ideal para cosecha y paisaje; primavera verde.' }, travelerProfile: { experienceType: 'Cultura y gastronomía', travelerProfile: 'Culturales, familias, foodies', suggestedStay: '1–2 noches', culturalLevel: 'Alta — mundo Menonita', landscapeType: 'Praderas, campos, llanura', role: 'Destino de contraste' }, cta: { primary: 'Ver paquetes relacionados', secondary: 'Cotizar viaje' } },
  'chihuahua': { subtitle: 'Capital señorial y arranque clásico hacia la Sierra', intro: 'Chihuahua es la ciudad que dio nombre al estado más grande de México: cantera, historia de la Revolución y haciendas que se pierden en el horizonte. Aquí Pancho Villa y la historia mexicana se palpan en cada edificio. Es el punto de partida oriental del Tren CHEPE y la base perfecta para quien quiere combinar ciudad, cultura y la subida épica a la Sierra Tarahumara.', whyGo: ['Capital histórica y arquitectura señorial', 'Cuna de la Revolución y museos', 'Punto de partida del CHEPE hacia la Sierra', 'Haciendas y rutas del desierto', 'Conectividad aérea y terrestre'], highlights: ['Historia y museos', 'Arquitectura y centro', 'Gastronomía norteña', 'Tren CHEPE', 'Haciendas y alrededores', 'Base de operaciones'], keyPlaces: ['Centro histórico', 'Museo de la Revolución (Quinta Gameros)', 'Catedral y Palacio de Gobierno', 'Haciendas (Quinta Carolina, etc.)', 'Estación del CHEPE', 'Mercado y gastronomía'], bestSeason: { when: 'Otoño y primavera; verano muy caliente.', climate: 'Desértico; inviernos fríos, veranos calurosos.', expect: 'Días despejados; noches frescas en otoño y primavera.' }, travelerProfile: { experienceType: 'Historia y ciudad', travelerProfile: 'Culturales, familias, quienes inician ruta CHEPE', suggestedStay: '1–2 noches', culturalLevel: 'Alta — historia y arquitectura', landscapeType: 'Ciudad, desierto, llanura', role: 'Base de inicio de ruta' }, cta: { primary: 'Ver paquetes relacionados', secondary: 'Hablar con un asesor' } },
}

const modalDataEn: Record<string, AtlasModalData> = {
  'creel': { subtitle: 'Base camp at the heart of the Sierra', intro: 'Creel beats at the very center of the Sierra Tarahumara: a town of wood and stone where time is measured in routes and Rarámuri stories. You don’t just pass through—you set up base to explore endless pine forests, valleys of mushrooms and petrified frogs, and the living presence of a culture that has endured for centuries. It’s the perfect starting point for those seeking depth, not just postcards.', whyGo: ['Natural gateway to the Sierra Tarahumara', 'Authentic connection with Rarámuri communities', 'Monumental nature minutes from town', 'Strategic logistics for routes to Divisadero and Barrancas', 'Iconic experiences: Valley of the Mushrooms, Arareco, missions'], highlights: ['Forest and rocky valley landscapes', 'Living Rarámuri culture', 'Local gastronomy and handicrafts', 'Mild to intense adventure', 'Viewpoints and lakes', 'Base for CHEPE and Barrancas tours'], keyPlaces: ['Lake Arareco', 'Valley of the Mushrooms', 'Valley of the Frogs', 'Tarahumara Cave', 'San Ignacio Mission', 'Connection to Divisadero and Copper Canyon'], bestSeason: { when: 'All year; fall and spring optimal.', climate: 'Mountain temperate; cold nights in winter.', expect: 'Rainy, green summer; dry winter and clear skies.' }, travelerProfile: { experienceType: 'Nature and culture', travelerProfile: 'Curious travelers, families, couples, moderate adventurers', suggestedStay: '2–4 nights as base', culturalLevel: 'High — direct encounter with communities', landscapeType: 'Pine forest, rocky valleys, lakes', role: 'Main operational base' }, cta: { primary: 'View related packages', secondary: 'Talk to an advisor' } },
  'barrancas-del-cobre': { subtitle: 'The undisputed epicenter of adventure in Mexico', intro: 'The Copper Canyon is not a single place: it’s a canyon system that multiplies human scale until it becomes insignificant. Here the earth opens into abysses over a thousand meters deep, the train winds along the slopes, and adventure—zip lines, trekking, viewpoints—is lived with an intensity few destinations in the world can match. Pure, wild, monumental nature.', whyGo: ['One of the largest canyon systems in the world', 'World-class adventure experiences', 'Views that redefine the idea of landscape', 'CHEPE crossing and cable car as unique experiences', 'Connection to Divisadero, Creel, and the Sierra'], highlights: ['Canyons and abysses', 'Cable car and train', 'Extreme and moderate adventure', 'Photography and viewpoints', 'Virgin nature', 'Organized tours from Creel and Divisadero'], keyPlaces: ['Adventure Park viewpoint', 'Barrancas cable car', 'CHEPE train route', 'Urique–Tararecua canyon system', 'Zip line and rappel points', 'Views of Copper Canyon'], bestSeason: { when: 'Fall to spring; avoid intense summer rains.', climate: 'Variable by elevation; cool at height, warm in canyon floor.', expect: 'Clear skies in dry season; intense green after rains.' }, travelerProfile: { experienceType: 'Adventure and extreme nature', travelerProfile: 'Adventurers, photographers, active couples', suggestedStay: '1–3 nights depending on circuit', culturalLevel: 'Medium — landscape and physical experience first', landscapeType: 'Canyons, abysses, forest', role: 'Star destination of the circuit' }, cta: { primary: 'View related packages', secondary: 'Explore experiences from here' } },
  'divisadero': { subtitle: 'The iconic CHEPE Train viewpoint and the cable car void', intro: 'Divisadero is the moment the journey stops before the abyss: three canyons converge at your feet and only the wind breaks the silence. The cable car crosses the void between cliffs; the train makes its mandatory stop. Here the experience is purely visual and sensory—an immersion in the brutal scale of the Sierra, with premium infrastructure that doesn’t strip the place of authenticity.', whyGo: ['View of the Three Canyons in one spot', 'Longest cable car in Latin America', 'Iconic stop of the CHEPE Train', 'Photography and unforgettable sunsets', 'Direct access to adventure and tranquility'], highlights: ['Panoramic viewpoints', 'Cable car', 'Photography and landscape', 'Local culture and crafts', 'Sunsets', 'Connectivity with Creel and Barrancas'], keyPlaces: ['Three Canyons viewpoint', 'CHEPE Train station', 'Barrancas cable car', 'Divisadero village', 'View to Urique and Tararecua', 'Trails and photo spots'], bestSeason: { when: 'All year; fall and spring with best light.', climate: 'Cool at altitude; sunny most of the year.', expect: 'Morning fog possible; clear afternoons ideal for photography.' }, travelerProfile: { experienceType: 'Panoramic and mild adventure', travelerProfile: 'All profiles; essential for CHEPE travelers', suggestedStay: '1–2 nights', culturalLevel: 'Medium — visual impact and train experience', landscapeType: 'Canyons, viewpoints, void', role: 'Panoramic point and connection' }, cta: { primary: 'View related packages', secondary: 'Get a quote' } },
  'el-fuerte': { subtitle: 'Colonial threshold before the epic ascent to the Sierra', intro: 'El Fuerte is the perfect prologue to the journey: a Magic Town where colonial architecture and the murmur of the Fuerte River tell centuries of history. Here you still feel the passage of the conquistadors and the legacy of the original cultures. It’s the western starting point of the CHEPE Train for those coming from the coast—a place to breathe, walk, and prepare the spirit before climbing into the mountains.', whyGo: ['Magic Town with intact colonial architecture', 'CHEPE starting point from the coast', 'Fuerte River and riverside nature', 'History and legends (Zorro)', 'Gastronomy and tranquility'], highlights: ['History and architecture', 'River and nature', 'Local gastronomy', 'Dances and traditions', 'Base for the CHEPE', 'Colonial identity'], keyPlaces: ['Historic center and Plaza de Armas', 'Fuerte River and waterfront', 'Museum and colonial buildings', 'Nearby communities', 'CHEPE Train station', 'Viewpoints and surroundings'], bestSeason: { when: 'Winter and spring; avoid extreme summer heat.', climate: 'Warm; mild in winter.', expect: 'Sunny days; pleasant nights; ideal for walking and photography.' }, travelerProfile: { experienceType: 'History and mild nature', travelerProfile: 'Culture seekers, families, CHEPE route starters', suggestedStay: '1–2 nights', culturalLevel: 'High — history and heritage', landscapeType: 'Colonial, river, vegetation', role: 'Route start base' }, cta: { primary: 'View related packages', secondary: 'Talk to an advisor' } },
  'los-mochis': { subtitle: 'Where the Sea of Cortez meets the start of the most astonishing train', intro: 'Los Mochis is the Pacific gateway to the Sierra Tarahumara: a city that lives from the sea and the land, with a gastronomy that draws travelers from across the country. Here the CHEPE journey begins—or ends—for those coming from the coast. It’s not just a logistical point: it’s a chance for fresh seafood, a port atmosphere, and the thrill of boarding the train toward the mountains.', whyGo: ['Start or end of the CHEPE Train from the coast', 'First-rate sea and land gastronomy', 'Air and land connectivity', 'Topolobampo port and Sea of Cortez', 'Ideal logistics for Creel–Divisadero routes'], highlights: ['Seafood and gastronomy', 'Port and beach', 'CHEPE Train', 'Services and connectivity', 'Coastal nature', 'Operations base'], keyPlaces: ['Downtown and dining area', 'Topolobampo port', 'CHEPE station', 'Parks and waterfront', 'Local markets', 'Connection to El Fuerte and Sinaloa'], bestSeason: { when: 'Fall to spring; very hot summer.', climate: 'Coastal warm; humidity in rainy season.', expect: 'Sun and breeze most of the year; ideal for seafood and outings.' }, travelerProfile: { experienceType: 'Gastronomy and logistics', travelerProfile: 'Route starters/finishers, sea lovers', suggestedStay: '1 night typical', culturalLevel: 'Medium — city and port', landscapeType: 'Coast, port, city', role: 'Coastal route ground zero' }, cta: { primary: 'View related packages', secondary: 'Explore experiences from here' } },
  'cerocahui': { subtitle: 'Jesuit refuge and vineyards in a hidden valley', intro: 'Cerocahui appears like a well-kept secret: a valley surrounded by mountains where a Jesuit mission and high-altitude vineyards coexist with silence. Here the experience is one of retreat and introspection—gentle walks, views of Urique Canyon, local wine, and the feeling of being far from the noise of the world. It’s the destination for those seeking depth and calm.', whyGo: ['Jesuit mission and historic heritage', 'High-altitude vineyards and local wine', 'Views of Urique Canyon from Gallego Overlook', 'Tranquility and retreat', 'Access to Barrancas with less tourist flow'], highlights: ['History and mission', 'Wine and vineyards', 'Canyon viewpoints', 'Gentle hiking', 'Local culture', 'Retreat stay'], keyPlaces: ['Cerocahui Mission', 'Gallego Overlook', 'Local vineyards', 'Cerocahui Valley', 'Connection to Urique', 'Trails and viewpoints'], bestSeason: { when: 'Fall to spring; summer with rain.', climate: 'Valley temperate; cool nights.', expect: 'Fall ideal for vineyards; spring green and in bloom.' }, travelerProfile: { experienceType: 'Culture and serene nature', travelerProfile: 'Travelers seeking calm, couples, retreats', suggestedStay: '1 night', culturalLevel: 'High — mission and wine', landscapeType: 'Valley, vineyards, canyon', role: 'Stay destination' }, cta: { primary: 'View related packages', secondary: 'Get a quote' } },
  'basaseachi': { subtitle: 'Mexico’s tallest permanent waterfall', intro: 'Basaseachi is home to Mexico’s tallest permanent waterfall: over 240 meters of free fall in a canyon of rock and pine forest. Water, stone, and nature come together in one of the most imposing scenes in the north. Trails, viewpoints, and the constant sound of water make the visit an experience that demands time and respect.', whyGo: ['Basaseachi Falls: Mexico’s tallest permanent waterfall', 'Pine forest and canyon landscape', 'Spectacular hiking and viewpoints', 'Virgin, well-preserved nature', 'Day trip or overnight experience'], highlights: ['Waterfall', 'Hiking', 'Forest and nature', 'Photography', 'Moderate adventure', 'Monumental landscape'], keyPlaces: ['Basaseachi Falls', 'Upper and lower viewpoint', 'Park trails', 'Candameña Forest', 'Connection from Creel or Chihuahua'], bestSeason: { when: 'Summer and fall—higher flow; spring also viable.', climate: 'Temperate to cool; rain in season.', expect: 'Falls most impressive after recent rain; green, humid summer.' }, travelerProfile: { experienceType: 'Nature and hiking', travelerProfile: 'Moderate adventurers, active families, photographers', suggestedStay: '1–2 nights', culturalLevel: 'Low—nature is the star', landscapeType: 'Waterfall, forest, canyon', role: 'Nature destination' }, cta: { primary: 'View related packages', secondary: 'Talk to an advisor' } },
  'guachochi': { subtitle: 'The Rarámuri heartland and gateway to Sinforosa Canyon', intro: 'Guachochi is the most authentic heart of the Sierra Tarahumara: a place where Rarámuri culture is not folklore but daily life. From here you reach the imposing Sinforosa Canyon and communities that keep their language, traditions, and resilience. It’s a destination for travelers seeking real cultural depth and landscapes few ever see.', whyGo: ['Largest concentration of Rarámuri population', 'Access to Sinforosa Canyon', 'Living, authentic culture', 'Less crowded landscapes', 'Community tourism experiences'], highlights: ['Rarámuri culture', 'Sinforosa Canyon', 'Community tourism', 'Hiking and adventure', 'Indigenous identity', 'Remote viewpoints'], keyPlaces: ['Guachochi town', 'Sinforosa Canyon', 'Rarámuri communities', 'Kokoyome and surroundings', 'Viewpoints and routes', 'Mission and cultural centers'], bestSeason: { when: 'March to November; avoid extreme winter cold.', climate: 'Highland temperate; cold nights.', expect: 'Dry season ideal for hiking; summer rain limits some routes.' }, travelerProfile: { experienceType: 'Indigenous culture and adventure', travelerProfile: 'Conscious travelers, culture seekers, adventurers', suggestedStay: '2–4 nights', culturalLevel: 'Very high — Rarámuri immersion', landscapeType: 'Sierra, canyon, communities', role: 'Depth destination' }, cta: { primary: 'View related packages', secondary: 'Explore experiences from here' } },
  'cuauhtemoc': { subtitle: 'Mennonite prairies and the apple of northern Mexico', intro: 'Cuauhtémoc surprises: in the midst of the arid north, Mennonite colonies maintain a way of life that seems frozen in time. Cheese, apples, buggies, and silence. The region is also the country’s leading apple producer. Here the experience is cultural and gastronomic—a unique contrast with the Sierra and desert that surround it.', whyGo: ['Mennonite colonies and unique culture', 'Mennonite gastronomy (cheese, cured meats)', 'Mexico’s most important apple region', 'Contrast with the Sierra and desert', 'Tranquility and safety'], highlights: ['Mennonite culture', 'Gastronomy and markets', 'Fields and prairies', 'Crafts and local products', 'Photography and landscape', 'Contrast experience'], keyPlaces: ['Mennonite colonies', 'Markets and cheese shops', 'Apple orchards', 'Cuauhtémoc city', 'Day routes', 'Connection to Creel and Chihuahua'], bestSeason: { when: 'All year; apple harvest in fall.', climate: 'Dry and temperate; cold winters.', expect: 'Fall ideal for harvest and landscape; green spring.' }, travelerProfile: { experienceType: 'Culture and gastronomy', travelerProfile: 'Culture seekers, families, foodies', suggestedStay: '1–2 nights', culturalLevel: 'High — Mennonite world', landscapeType: 'Prairies, fields, plains', role: 'Contrast destination' }, cta: { primary: 'View related packages', secondary: 'Get a quote' } },
  'chihuahua': { subtitle: 'Stately capital and classic start toward the Sierra', intro: 'Chihuahua is the city that gave its name to Mexico’s largest state: stonework, Revolution history, and haciendas that stretch to the horizon. Here Pancho Villa and Mexican history are palpable in every building. It’s the eastern starting point of the CHEPE Train and the perfect base for combining city, culture, and the epic climb into the Sierra Tarahumara.', whyGo: ['Historic capital and stately architecture', 'Cradle of the Revolution and museums', 'CHEPE starting point toward the Sierra', 'Haciendas and desert routes', 'Air and land connectivity'], highlights: ['History and museums', 'Architecture and downtown', 'Northern gastronomy', 'CHEPE Train', 'Haciendas and surroundings', 'Operations base'], keyPlaces: ['Historic center', 'Revolution Museum (Quinta Gameros)', 'Cathedral and Government Palace', 'Haciendas (Quinta Carolina, etc.)', 'CHEPE station', 'Market and gastronomy'], bestSeason: { when: 'Fall and spring; very hot summer.', climate: 'Desert; cold winters, hot summers.', expect: 'Clear days; cool nights in fall and spring.' }, travelerProfile: { experienceType: 'History and city', travelerProfile: 'Culture seekers, families, CHEPE route starters', suggestedStay: '1–2 nights', culturalLevel: 'High — history and architecture', landscapeType: 'City, desert, plains', role: 'Route start base' }, cta: { primary: 'View related packages', secondary: 'Talk to an advisor' } },
}

export type LocaleAtlas = 'es' | 'en'

export function getAtlasData(locale: LocaleAtlas): { destinations: AtlasDestination[]; modalData: Record<string, AtlasModalData> } {
  return locale === 'en'
    ? { destinations: destinationsEn, modalData: modalDataEn }
    : { destinations: destinationsEs, modalData: modalDataEs }
}
